import { http, HttpResponse, type HttpHandler } from 'msw';
import type { TutorStudent } from './types';

/** SPEC-SCREENS §5 mock (6 ta). */
export const mockStudents: TutorStudent[] = [
  {
    id: 's-341030',
    name: 'Aliyev Akmal',
    hemisId: '341030',
    group: '412-22',
    company: 'Tech Solutions MChJ',
    attendancePct: 94,
    attendedDays: 34,
    totalDays: 36,
    diaryCount: 32,
    diaryAvg: 4.2,
    state: 'active',
    suspiciousCount: 0,
  },
  {
    id: 's-341031',
    name: 'Karimov Bekzod',
    hemisId: '341031',
    group: '412-22',
    company: 'Agrobank ATB',
    attendancePct: 86,
    attendedDays: 31,
    totalDays: 36,
    diaryCount: 28,
    diaryAvg: 3.8,
    state: 'active',
    suspiciousCount: 0,
  },
  {
    id: 's-341032',
    name: 'Sobirov Diyor',
    hemisId: '341032',
    group: '413-22',
    company: 'Uzinfocom',
    attendancePct: 64,
    attendedDays: 23,
    totalDays: 36,
    diaryCount: 19,
    diaryAvg: 3.1,
    state: 'redFlag',
    suspiciousCount: 0,
  },
  {
    id: 's-341033',
    name: 'Yusupova Nilufar',
    hemisId: '341033',
    group: '413-22',
    company: 'Mediapark',
    attendancePct: 100,
    attendedDays: 36,
    totalDays: 36,
    diaryCount: 36,
    diaryAvg: 4.8,
    state: 'active',
    suspiciousCount: 0,
  },
  {
    id: 's-341034',
    name: 'Rahimov Sardor',
    hemisId: '341034',
    group: '412-22',
    company: 'Qurilish Trest 12',
    attendancePct: 78,
    attendedDays: 28,
    totalDays: 36,
    diaryCount: 25,
    diaryAvg: 3.5,
    state: 'suspicious',
    suspiciousCount: 3,
  },
  {
    id: 's-341035',
    name: 'Toshpulatova Zarina',
    hemisId: '341035',
    group: '413-22',
    company: 'Ipak Yuli Bank',
    attendancePct: 89,
    attendedDays: 32,
    totalDays: 36,
    diaryCount: 30,
    diaryAvg: 4.0,
    state: 'active',
    suspiciousCount: 0,
  },
];

export const studentsHandlers: HttpHandler[] = [
  http.get('/api/tutor/students', () => HttpResponse.json(mockStudents)),
];
